# Copyright (c) 2022 Nitro Agility S.r.l.
# SPDX-License-Identifier: Apache-2.0

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from permguard.data.v1 import pdp_pb2 as permguard_dot_data_dot_v1_dot_pdp__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in permguard/data/v1/pdp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolicyDecisionPointStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Evaluate = channel.unary_unary(
                '/permguard.data.v1.PolicyDecisionPoint/Evaluate',
                request_serializer=permguard_dot_data_dot_v1_dot_pdp__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=permguard_dot_data_dot_v1_dot_pdp__pb2.EvaluateResponse.FromString,
                _registered_method=True)
        self.EvaluateMany = channel.unary_unary(
                '/permguard.data.v1.PolicyDecisionPoint/EvaluateMany',
                request_serializer=permguard_dot_data_dot_v1_dot_pdp__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=permguard_dot_data_dot_v1_dot_pdp__pb2.EvaluateResponse.FromString,
                _registered_method=True)
        self.GetConfiguration = channel.unary_unary(
                '/permguard.data.v1.PolicyDecisionPoint/GetConfiguration',
                request_serializer=permguard_dot_data_dot_v1_dot_pdp__pb2.GetConfigurationRequest.SerializeToString,
                response_deserializer=permguard_dot_data_dot_v1_dot_pdp__pb2.GetConfigurationResponse.FromString,
                _registered_method=True)


class PolicyDecisionPointServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateMany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyDecisionPointServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=permguard_dot_data_dot_v1_dot_pdp__pb2.EvaluateRequest.FromString,
                    response_serializer=permguard_dot_data_dot_v1_dot_pdp__pb2.EvaluateResponse.SerializeToString,
            ),
            'EvaluateMany': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateMany,
                    request_deserializer=permguard_dot_data_dot_v1_dot_pdp__pb2.EvaluateRequest.FromString,
                    response_serializer=permguard_dot_data_dot_v1_dot_pdp__pb2.EvaluateResponse.SerializeToString,
            ),
            'GetConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfiguration,
                    request_deserializer=permguard_dot_data_dot_v1_dot_pdp__pb2.GetConfigurationRequest.FromString,
                    response_serializer=permguard_dot_data_dot_v1_dot_pdp__pb2.GetConfigurationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'permguard.data.v1.PolicyDecisionPoint', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('permguard.data.v1.PolicyDecisionPoint', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyDecisionPoint(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permguard.data.v1.PolicyDecisionPoint/Evaluate',
            permguard_dot_data_dot_v1_dot_pdp__pb2.EvaluateRequest.SerializeToString,
            permguard_dot_data_dot_v1_dot_pdp__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateMany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permguard.data.v1.PolicyDecisionPoint/EvaluateMany',
            permguard_dot_data_dot_v1_dot_pdp__pb2.EvaluateRequest.SerializeToString,
            permguard_dot_data_dot_v1_dot_pdp__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/permguard.data.v1.PolicyDecisionPoint/GetConfiguration',
            permguard_dot_data_dot_v1_dot_pdp__pb2.GetConfigurationRequest.SerializeToString,
            permguard_dot_data_dot_v1_dot_pdp__pb2.GetConfigurationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
